services:
  astrocore-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: astrocore-backend
    environment:
      TZ: Asia/Shanghai
    volumes:
      - C:/AstroCoreData/data:/app/backend/data
      - C:/AstroCoreData/storage:/app/backend/storage
    ports:
      - "8000:8000"
    restart: unless-stopped

  astrocore-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: astrocore-frontend
    environment:
      TZ: Asia/Shanghai
    ports:
      - "3000:80"
    depends_on:
      - astrocore-backend
    restart: unless-stopped