services:
  astrocore-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astrocore-backend
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      # 自定义数据库目录
      - C:/AstroCoreData/data:/app/backend/data

      # 自定义上传文件目录
      - C:/AstroCoreData/storage:/app/backend/storage
    restart: unless-stopped